#if !canImport(ObjectiveC)
import XCTest

extension SudokuTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SudokuTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SudokuTests.__allTests__SudokuTests),
    ]
}
#endif
